---
version: "2.0"

services:
  node-web-app:
    image: cleik/test-repo
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true

profiles:
  compute:
    node-web-app:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      pricing:
        node-web-app: 
          denom: uakt
          amount: 100

deployment:
  node-web-app:
    akash:
      profile: node-web-app
      count: 1
